name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create deployment directory
        run: mkdir -p deploy

      - name: Copy static files
        run: |
          # Copy required files
          if [ ! -f "public/index.html" ]; then
            echo "Error: index.html not found"
            exit 1
          fi
          if [ ! -f "public/client.js" ]; then
            echo "Error: client.js not found"
            exit 1
          fi
          cp public/index.html deploy/
          cp public/client.js deploy/
          
          # Copy optional files if they exist
          if [ -f "public/client.js.map" ]; then
            cp public/client.js.map deploy/
          fi

      - name: Verify deployment files
        run: |
          echo "Checking deployment files..."
          ls -la deploy/
          if [ ! -f "deploy/index.html" ] || [ ! -f "deploy/client.js" ]; then
            echo "Error: Required files are missing in deployment directory"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 